name: Visit Page Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *" # Esto ejecuta el trabajo cada 5 minutos
  workflow_dispatch: # Permite la ejecución manual

jobs:
  visit_page:
    runs-on: ubuntu-latest # Usa un runner hospedado por GitHub
    steps:
      - name: Make HTTP request
        run: |
          curl https://p-web.onrender.com  # Reemplaza con la URL que deseas visitar
